### ISSUE TITLE
Class-Room Information data insertion breaks

### ISSUE THREAD

**Issue by monjurmorshed793** [apu84/UMS#3]
When, more than 30 data are input in the the class-room info, then, insertion halts. While inserting data, the insertion rows should be at the bottom, but, the insertion row opens somewhere above the last row, for example, I want to insert a new data at 30 row, but, the insertion column opens at 21 line. 
The issue must be solved.

**Comment by apu84** [comment]
Scroll doesn't seem to work well with added row. So scrolling is disabled by default, rather added pagination.
